
version: '2'
services:
  db:
    restart: always
    image: postgres:9.4
    environment:
      - DB_PASS=secretpassword
    ports:
        - "5433:5432"  

  wildfly:
    environment:
      - KEYCLOAK_USER=adam
      - KEYCLOAK_PASSWORD=password

    build: .
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8443:8443"
      - "8787:8787" 
